name: Gonzalo Mateo Garc√≠a
markdown: kramdown
permalink: blog/:year/:month/:day/:title
# baseurl: /gonmagar
exclude: [publications/Untitled.ipynb, Gemfile, Gemfile.lock, publications/index_2.html, publications/template_pubs.tpl, LICENSE, blog/notebooks/]
